title: Shivani Shankar # your name (or website title) here
logo: "/profiles.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
 Software Developer Engineer
  <br><br>
  <a href="shivanishankar.15@gmail.com">shivanishankar.15@gmail.com </a>
  <br>
  <a href="https://www.linkedin.com/in/shivani-shankar15/">LinkedIn Profile</a>
  <br>
  <a href="https://www.gihub.com/Shivani1502/">Gihub</a> 
theme: jekyll-theme-minimal
